### ISSUE TITLE
About Real Dataset Evaluation 

### ISSUE THREAD

**Issue by 61966** [cschenxiang/HCT-FFN#1]
Nice work!
I saw in the article that an indicator evaluation was conducted on a real dataset. Can you provide an evaluation code for the NIQE/BRISQUE indicator

**Comment by cschenxiang** [comment]
> Nice work! I saw in the article that an indicator evaluation was conducted on a real dataset. Can you provide an evaluation code for the NIQE/BRISQUE indicator

https://github.com/cschenxiang/DRSformer/blob/main/evaluations/Evaluation_Real/eval_niqe_brisque.py
